export const clerkAuthAppearance = {
  options: {
    elevation: "flush",
  },
  variables: {
    colorPrimary: "#4d5a4b",
    colorForeground: "#33302a",
    colorMutedForeground: "#837d6f",
    colorBackground: "#faf8f2",
    colorInput: "#ffffff",
    colorInputForeground: "#33302a",
    colorBorder: "#ddd6c6",
    colorRing: "#6e7a6b",
    colorDanger: "#943f32",
    borderRadius: "0.625rem",
    fontFamily: "var(--font-ui)",
  },
  elements: {
    rootBox: "auth-clerk-root",
    cardBox: "auth-clerk-card-box",
    card: "auth-clerk-card",
    header: "auth-clerk-hidden",
    formFieldLabel: "auth-clerk-label",
    formFieldInput: "auth-clerk-input",
    formButtonPrimary: "auth-clerk-submit",
    formFieldAction: "auth-clerk-action",
    footer: "auth-clerk-footer",
    footerActionText: "auth-clerk-footer-text",
    footerActionLink: "auth-clerk-footer-link",
    socialButtonsBlockButton: "auth-clerk-social-button",
    dividerLine: "auth-clerk-divider",
    dividerText: "auth-clerk-divider-text",
    identityPreview: "auth-clerk-identity",
    otpCodeFieldInput: "auth-clerk-otp",
  },
} as const;
